### ISSUE TITLE
现在还有冻屏的现象吗？

### ISSUE THREAD

**Issue by SuperPDX** [reputati0n/hackintosh-b360--9400f#1]
和你的配置差不多，之前也是用的imac pro 1.1，但是总是冻屏，后来就换成iMac 19,1，不会冻屏，但是硬解就有点不完美

你的现在还有冻屏的现象吗？

**Comment by reputati0n** [comment]
系统更新为macos mojave 10.14.6之后冻屏现象消失，猜测原因为10.14.5硬解方案不完美导致的，可以尝试升级10.14.6
