### ISSUE TITLE
请问这个显示硬件信息视频解码信息的这个软件是什么？

### ISSUE THREAD

**Issue by shelken** [reputati0n/hackintosh-b360--9400f#2]
请问这个显示硬件信息视频解码信息的这个软件是什么？还有请问无核显的cpu使用过程会有什么问题吗？听说无核显无法硬件加速？

**Comment by reputati0n** [comment]
软件为VideoProc，无核显CPU开启硬解需要配合RX4/5系显卡，设置机型为iMac Pro1.1，升级系统到10.14.6即可自动开启硬解

**Comment by shelken** [comment]
好的，多谢了
