### ISSUE TITLE
DW1820A无线网卡插入后开机不正常，点击所有按钮没反应。

### ISSUE THREAD

**Issue by benizhang** [reputati0n/hackintosh-b360--9400f#4]
你好，请问一下，我组装主机时候找EFI发现你的配置是跟我的几乎一样，MSI B360M 迫击炮+i5 9400F+蓝宝石RX570 4G，发现出了内存和硬盘之外是一模一样的。所以也跟你选购同款网卡，使用转接卡，在10.14.6下使用你的EFI，装好后没什么问题，但插上这张网卡之后开机进入系统后感觉整个界面卡死，很慢，按什么都没反应，最后要通过电源强制关机，不插网卡一切正常。这种情况是我的驱动没打好？（我直接使用你的EFI覆盖的）还是其他什么原因，我是4k显示器，网卡的WiFi和蓝牙在win10可以正常使用。
还有看到你在https://github.com/reputati0n/hackintosh-b360--9400f/issues/3 的回复是插在第二个pcie，我是因为显卡插在第一个pcie x16，中间两个都有点被挡住了，所以网卡是插在第四个pcie的，会不会是存在插槽插错的问题呢？请问你的网卡是怎么插的才能不会挡住第二个pcie呢？
ps：我的网卡转接卡应该是pcie x1的，我把它插在pcie x16插槽。

**Comment by reputati0n** [comment]
与安装位置关系不大，部分版本的DW1820A可能需要屏蔽针脚才能在macOS下正常使用，具体屏蔽方法可以参考[黑果小兵的教程](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)，如果实在无法正常使用，可以选择苹果原装卡BCM94360CS2，插上即可使用，不需要额外的折腾。

**Comment by benizhang** [comment]
嗯嗯，就是很奇怪，我跟你是同样的配置来着。再问一个，你的有进行屏蔽吗？

**Comment by benizhang** [comment]
是不是正常来说我直接复制你的EFI不用再进行额外改动就可以的了。

**Comment by reputati0n** [comment]
正常情况下，你的配置可以直接用我的EFI完美驱动的，我的网卡并没有进行屏蔽就直接在win10/macos下正常使用，但是鉴于DW1820A有多个版本，所以不敢保证所有版本一定完美使用

**Comment by benizhang** [comment]
能告知你所使用的版本号吗？

**Comment by reputati0n** [comment]
编号CN-0VW3T3，版本A00
