### ISSUE TITLE
冻屏问题解决了么

### ISSUE THREAD

**Issue by wxjer** [reputati0n/hackintosh-b360--9400f#5]
从你文章过来的，rx570 8g，10.15.0 开机用一会儿就不能动了，键盘也没反应，后台声音一直卡在最后一个音上

**Comment by reputati0n** [comment]
冻屏问题在我升级到10.14.6之后就消失了，猜测是硬解的关系，不过具体的原因在远景也没有讨论出什么结果，tonymacx86也没有得到具体答案，只能暂时视为玄学，可以尝试更换下其他机型的SMBIOS。

**Comment by wxjer** [comment]
昨天加了参数 -rad4000 目前还没出现冻屏
目前是睡眠就崩了哈

**Comment by kundaria** [comment]
does it support apple sidecar to connect ipad as second display?

**Comment by reputati0n** [comment]
It is supported, but I don't have an ipad, so my EFI is not set. The specific method can refer to this post.
!(pcbeta)[http://bbs.pcbeta.com/viewthread-1829618-1-1.html]

**Comment by reputati0n** [comment]
It is supported, but I don't have an ipad, so my EFI is not set. The specific method can refer to this post.
[pcbeta](http://bbs.pcbeta.com/viewthread-1829618-1-1.html)
