### ISSUE TITLE
内存频率问题

### ISSUE THREAD

**Issue by thehappymouse** [reputati0n/hackintosh-b360--9400f#7]
你好，看好你的黑果配置，板U 欲想同，但内存这块有疑惑

U的说明：内存类型 | DDR4 2666/2400/2133MHz
板的说明：内存描述 | 支持双通道DDR4 2666/2400/2133MHz内存

简单理解，频率上限2600，那么您的影驰极光 3600的频率是否无法发挥？

**Comment by reputati0n** [comment]
B360主板内存频率最高支持到2666，我的影驰极光买的是2400频率的，自行超频到了2666使用
