### ISSUE TITLE
显卡rx590问题

### ISSUE THREAD

**Issue by yang123-w** [reputati0n/hackintosh-b360--9400f#8]
使用rx590蓝宝石可以吗？谢谢

**Comment by reputati0n** [comment]
可以，RX570/580 2304SP/590都免驱

**Comment by yang123-w** [comment]
还有就是我现在用的是10.14.5的版本，网上面说这个版本可以独显双硬解，不知道用你的efi可以不？谢谢！

**Comment by reputati0n** [comment]
可以，无核显cpu搭配rx/vega系列独显在10.14.5之后的版本中，将机型设置为iMacPro1.1是可以完美硬解的，我的EFI已经设置好了
